name: Main

on:
  push:
    branches:
      - main

env:
  LANG: en_US.UTF-8
  
  # Fastlane
  FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
  FASTLANE_TEAM_NAME: ${{ secrets.FASTLANE_TEAM_NAME }}
  
  ## Certificate Management
  MATCH_READONLY: true
  MATCH_TYPE: 'development'
  MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
  MATCH_GIT_BRANCH: ${{ secrets.MATCH_GIT_BRANCH }}
  MATCH_GIT_FULL_NAME: ${{ secrets.MATCH_GIT_FULL_NAME }}
  MATCH_GIT_USER_EMAIL: ${{ secrets.MATCH_GIT_USER_EMAIL }}
  MATCH_APP_IDENTIFIER: ${{ secrets.MATCH_APP_IDENTIFIER }}
  MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
  
  # Notifications
  SLACK_URL: ${{ secrets.SLACK_URL }}
  SLACK_CHANNEL: '#mobile'

jobs:
  build:
    runs-on: macos
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bootstrap developer environment
      run: echo make bootstrap # Disabled until GitHub Actions Runner released for M1
    - name: Lint the repository
      run: make lint
